// Generates public/version.js at build time.
//
// The version comes from package.json (bump it with `npm version patch|minor|
// major`, which also tags the commit). The date is the build date, so it always
// reflects when the live site was actually deployed rather than whenever
// someone last remembered to edit a literal.
//
// The output file is gitignored: it is a build artifact, and committing it
// would mean every deploy dirties the working tree.

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "version.js");

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function formatDate(d) {
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${day}-${MONTHS[d.getUTCMonth()]}-${d.getUTCFullYear()}`;
}

function commitSha() {
  // Vercel exposes the SHA as an env var; the git call is the local fallback.
  if (process.env.VERCEL_GIT_COMMIT_SHA) {
    return process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 7);
  }
  try {
    return execSync("git rev-parse --short HEAD", {
      cwd: ROOT,
      stdio: ["ignore", "pipe", "ignore"],
    }).toString().trim();
  } catch {
    return null; // not a git checkout (e.g. a source tarball)
  }
}

const { version } = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const now = new Date();

const build = {
  version,
  date: formatDate(now),
  iso: now.toISOString().slice(0, 10),
  commit: commitSha(),
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `/* Generated by scripts/stamp-version.mjs — do not edit. */\n` +
    `window.__POMOFLOW_BUILD__ = ${JSON.stringify(build)};\n`,
  "utf8"
);

console.log(`stamped v${build.version} (${build.date}, ${build.commit ?? "no commit"})`);
